# Generated by Django 4.2.30 on 2026-07-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('TEACHER', 'Учитель'), ('STUDENT', 'Ученик'), ('PARENT', 'Родитель')], default='STUDENT', max_length=20, verbose_name='Роль'),
        ),
    ]
