[mypy]
python_version = 3.11
plugins = mypy_django_plugin.main
warn_unused_ignores = True
ignore_missing_imports = True
exclude = (migrations|staticfiles)/

[mypy.plugins.django-stubs]
django_settings_module = core.settings

[mypy-*.migrations.*]
ignore_errors = True
[mypy-*.admin]
ignore_errors = True