# Generated by Django 4.2.30 on 2026-07-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0003_schedule_slug_alter_grade_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="",
                max_length=150,
                unique=True,
                verbose_name="URL-слаг",
            ),
        ),
    ]
