# Generated by Django 4.2.30 on 2026-07-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0004_alter_schedule_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grade",
            options={
                "ordering": ["-date"],
                "verbose_name": "Grade",
                "verbose_name_plural": "Grades",
            },
        ),
        migrations.AlterField(
            model_name="grade",
            name="value",
            field=models.PositiveSmallIntegerField(verbose_name="Grade"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="weekday",
            field=models.IntegerField(
                choices=[
                    (1, "Monday"),
                    (2, "Tuesday"),
                    (3, "Tuesday"),
                    (4, "Thursday"),
                    (5, "Friday"),
                    (6, "Saturday"),
                ],
                verbose_name="День недели",
            ),
        ),
    ]
