# Generated by Django 4.2.30 on 2026-08-01 16:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gradebook", "0005_alter_grade_options_alter_grade_value_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name": "Class", "verbose_name_plural": "Classes"},
        ),
        migrations.AlterModelOptions(
            name="homework",
            options={"verbose_name": "Homework", "verbose_name_plural": "Homework"},
        ),
        migrations.AlterModelOptions(
            name="schedule",
            options={"verbose_name": "Schedule", "verbose_name_plural": "Schedule"},
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"verbose_name": "Subject", "verbose_name_plural": "Subjects"},
        ),
        migrations.AlterField(
            model_name="grade",
            name="comment",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Comment"
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Date given"
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "STUDENT"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Student",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="gradebook.subject",
                verbose_name="Subject",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="teacher",
            field=models.ForeignKey(
                limit_choices_to={"role": "TEACHER"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="given_grades",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Teacher",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Class name"),
        ),
        migrations.AlterField(
            model_name="group",
            name="year",
            field=models.PositiveIntegerField(verbose_name="Academic year"),
        ),
        migrations.AlterField(
            model_name="homework",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="homework",
            name="date",
            field=models.DateField(verbose_name="Assigned date"),
        ),
        migrations.AlterField(
            model_name="homework",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homeworks",
                to="gradebook.schedule",
                verbose_name="Scheduled lesson",
            ),
        ),
        migrations.AlterField(
            model_name="homework",
            name="task",
            field=models.TextField(verbose_name="Task"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="classroom",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Classroom"
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="gradebook.group",
                verbose_name="Class",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="lesson_number",
            field=models.PositiveIntegerField(verbose_name="Lesson number"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="",
                max_length=150,
                unique=True,
                verbose_name="URL slug",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="gradebook.subject",
                verbose_name="Subject",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="teacher",
            field=models.ForeignKey(
                limit_choices_to={"role": "TEACHER"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teacher_schedules",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Teacher",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="weekday",
            field=models.IntegerField(
                choices=[
                    (1, "Monday"),
                    (2, "Tuesday"),
                    (3, "Wednesday"),
                    (4, "Thursday"),
                    (5, "Friday"),
                    (6, "Saturday"),
                ],
                verbose_name="Weekday",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Subject name"),
        ),
    ]
