# Generated by Django 4.2.30 on 2026-08-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0006_alter_group_options_alter_homework_options_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["student", "-date"], name="grade_student_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["subject", "-date"], name="grade_subject_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="homework",
            index=models.Index(
                fields=["schedule", "-date"], name="hw_schedule_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(
                fields=["group", "weekday"], name="sched_group_weekday_idx"
            ),
        ),
    ]
