# Generated by Django 4.2.30 on 2026-08-11 11:46

from django.db import migrations


CREATE_FUNCTION = """
CREATE OR REPLACE FUNCTION student_average(p_student_id integer)
RETURNS numeric AS $$
DECLARE
    avg_value numeric;
BEGIN
    SELECT ROUND(AVG(value)::numeric, 2)
    INTO avg_value
    FROM gradebook_grade
    WHERE student_id = p_student_id;

    RETURN avg_value;  
END;
$$ LANGUAGE plpgsql STABLE;
"""
DROP_FUNCTION = "DROP FUNCTION IF EXISTS student_average(integer);"


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0007_grade_grade_student_date_idx_and_more"),
    ]

    operations = [
        migrations.RunSQL(sql=CREATE_FUNCTION, reverse_sql=DROP_FUNCTION),
    ]